# -*- coding: utf-8 -*-
"""MediaAlunos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_hLvPpeCb9Fdbaj6AB_TSIJ1Meoxmc1N
"""

nota1 = float( input('Nota 1: '))
nota2 = float( input('Nota 2: '))
nota3 = float( input('Nota 3: '))
media = (nota1 + nota2 + nota3) / 3
if (media >= 7):
    sit = 'Aprovado'
elif (media >=4):
    sit = 'Recuperação'
else:
    sit = 'Reprovado'        
print(f'O aluno está {sit} com média {media:.2f}')